### ISSUE TITLE
Don't specify python versions for install steps

### ISSUE THREAD

**Issue by adamcee** [codeplatoon-fullstack/installfest#1]
Example:
https://github.com/codeplatoon-fullstack/installfest/tree/main/Windows

```
    #the following installation will give python the ability to create
    #virtual environments
    sudo apt install python3.8-venv
```

**Comment by fravila08** [comment]
Worked through the install fest on a separate machine with a student and found a couple of issues if we don't specify the python version. We will at least need `python3-venv` for this command to work.

**Comment by adamcee** [comment]
A million years late @fravila08 but 👍 . Closing this issue : )
